config/routes.rb
Rails.application.routes.draw do
  resources :directions
  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  get 'styleguide/index'
  devise_for :users

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  	post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
get 'users/:id/following', :to => "users#following", :as => :following
resources :subscribers
  resources :posts do
	resources :comments
  resources :likes
  resources :favorites
end
get 'about/index'
get 'promo/index'
  get 'posts/index'
  get 'directions/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'directions', to: 'directions#index'
  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'
  root 'promo#index'
  # root 'direction#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
		belongs_to :user
end

app/models/direction.rb
class Direction < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		mount_uploader :image, ImageUploader
			belongs_to :user
			belongs_to :category
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
has_many :followees, through: :followed_users
has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
has_many :followers, through: :following_users
has_many :likes, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :favorited_posts, :through => :favorites, :source => :post
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  before_action :set_direction, only: %i[ show edit update destroy ]

  # GET /directions or /directions.json
  def index
    @directions = Direction.all
  end

  # GET /directions/1 or /directions/1.json
  def show
  end

  # GET /directions/new
  def new
    @direction = Direction.new
  end

  # GET /directions/1/edit
  def edit
  end

  # POST /directions or /directions.json
  def create


  # PATCH/PUT /directions/1 or /directions/1.json
  def update
    respond_to do |format|
      if @direction.update(direction_params)
        format.html { redirect_to @direction, notice: "Direction was successfully updated." }
        format.json { render :show, status: :ok, location: @direction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directions/1 or /directions/1.json
  def destroy
    @direction.destroy
    respond_to do |format|
      format.html { redirect_to directions_url, notice: "Direction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direction
      @direction = Direction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def direction_params
      params.require(:direction).permit(:name, :title, :content)
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/styleguide_helper.rb
module StyleguideHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/directions/_form.html.erb
<%= form_with(model: direction) do |form| %>
  <% if direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(direction.errors.count, "error") %> prohibited this direction from being saved:</h2>

      <ul>
        <% direction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4 class="form__block__title1">Вид класса</h4>
    <%= form.text_field :name, :class => "form3"  %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/directions/edit.html.erb
<h1>Отредактрировать</h1>

<%= render 'form', direction: @direction %>

<%= link_to 'Show', @direction %> |
<%= link_to 'Back', directions_path %>

app/views/directions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Классы</h1>

<div class="link2">
  <%= link_to "о проекте", about_path %>
</div>
<div class="link1">
  <%= link_to "промо", promo_path %>
</div>
<div class="link3">
  <%= link_to "афиша", posts_path %>
</div>
<div class="link333">
<%= link_to "классы", directions_path %>
</div>

<% if user_signed_in? && current_user.isadmin == true %>

<%= link_to 'Новый класс', new_direction_path %>
<% end %>

<tbody class="directions">

  <% @directions.each do |direction| %>
  <td>

  <td><%= direction.category.name %></td>
    <tr class="posts__item">
<td><%= post.content.html_safe %></td>
      <td class="posts__item__text posts__item__text-theme"><%= direction.name %></td>
       <td class="posts__item__text posts__item__text-title"><%= direction.title %></td>


<td class="posts__item__links">

        <%= link_to 'Открыть', direction, :class =>"link" %>

<% if user_signed_in? && current_user.isadmin == true %>

      <%= link_to 'Изменить', edit_direction_path(post), :class =>"link" %>


      <%= link_to 'Удалить', direction, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"link" %>
<% end %>
    </td>

    </tr>

</tbody>
</table>


<% end %>

app/views/directions/new.html.erb
<h1>Новый класс или направление</h1>

<%= render 'form', direction: @direction %>

<%= link_to 'Back', directions_path %>

app/views/directions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @direction.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @direction.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @direction.content %>
</p>



<%= link_to 'Edit', edit_direction_path(@direction) %> |
<%= link_to 'Back', directions_path %>