config/routes.rb
Rails.application.routes.draw do
  resources :directions
  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  get 'styleguide/index'
  devise_for :users

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  	post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
get 'users/:id/following', :to => "users#following", :as => :following
resources :subscribers
  resources :posts do
	resources :comments
  resources :likes
  resources :favorites
end
get 'about/index'
get 'promo/index'
  get 'posts/index'
  get 'directions/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'directions', to: 'directions#index'
  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'
  root 'promo#index'
  # root 'direction#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
		belongs_to :user
end

app/models/direction.rb
class Direction < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		mount_uploader :image, ImageUploader
			belongs_to :user
			belongs_to :category
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
has_many :followees, through: :followed_users
has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
has_many :followers, through: :following_users
has_many :likes, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :favorited_posts, :through => :favorites, :source => :post
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    if @user
      @posts = @user.favorited_posts
      render actions: :show
      @favorites = @user.favorites.all
    else
        render file: 'public/404', status: 404, formats: [:html]
    end
  end

def favorited?(post)
    favorites.find_by(post_id: post.id).present?
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end

  def following
    @user = User.find(params[:id])
    if @user
      @follow = @user.followed_users
      render actions: :show
      @following = @user.followees.all
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/styleguide_helper.rb
module StyleguideHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/following.html.erb
<% @follow.each do |follow| %>
  <br><%= link_to follow.followee_id, user_path(follow.followee_id)  %>
  <%= link_to User.find(follow.followee_id).username, user_path(follow.followee_id)  %>
<% end %>

app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Username</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, user %></td>
        <td><%= user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>ID <%= @user.id %></p>
<p>Email <%= @user.email %></p>
<p>Username <%= @user.username %></p>
<% if user_signed_in? && current_user.isadmin == true %>
  <p>Admin <%= @user.isadmin %></p>
<% end %>
<p>Followers <%= @user.followers.count %></p>
<p>Following <%= link_to @user.followees.count, following_path %></p>

<% if user_signed_in? && @user.id == current_user.id %>
	<p><%= link_to 'Edit profile', edit_user_registration_path %></p>
<% end %>

In favorites <%= @user.favorites.count %> <%= (@user.favorites.count) == 1 ? 'Post' : 'Posts'%>
<% @posts.each do |post| %>
  <br><%= link_to post.title, post %><%= post.category.name %>
<% end %>

<% if user_signed_in? && @user.id == current_user.id %>
    <%= link_to 'Edit Profile', edit_user_registration_path %>
<% elsif user_signed_in? && current_user.followees.include?(@user) %>
    <h5><%= button_to "Unfollow", unfollow_user_path, method: "POST" %></h5>
<% elsif user_signed_in? %>
    <h5><%= button_to "Follow", follow_user_path, method: "POST"  %></h5>
<% else %>
<%# можно добавить кнопку для регистрации или что-нибудь ещё  %>
<% end%>