config/routes.rb
Rails.application.routes.draw do
  resources :directions
  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  get 'styleguide/index'
  devise_for :users

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  	post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
get 'users/:id/following', :to => "users#following", :as => :following
resources :subscribers
  resources :posts do
	resources :comments
  resources :likes
  resources :favorites
end
get 'about/index'
get 'promo/index'
  get 'posts/index'
  get 'directions/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'directions', to: 'directions#index'
  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'
  root 'promo#index'
  # root 'direction#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
		belongs_to :user
end

app/models/direction.rb
class Direction < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		mount_uploader :image, ImageUploader
			belongs_to :user
			belongs_to :category
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
has_many :followees, through: :followed_users
has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
has_many :followers, through: :following_users
has_many :likes, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :favorited_posts, :through => :favorites, :source => :post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # http_basic_authenticate_with :name => "admin", :password => "superstrongpassword", :except => [:index, :show]
before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
	params.require(:post).permit(:name, :title, :content, :image, :category_id)
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/styleguide_helper.rb
module StyleguideHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4 class="form__block__title1">Вид мероприятия</h4>
    <%= form.text_field :name, :class => "form3" %>
  </div>

  <div class="field">
      <%= form.label :category_id %>
      <%= form.select :category_id, Category.pluck(:name, :id) %>
  </div>


  <div>
    <h4 class="form__block__title4">Загрузите изображение</h4>
  </div>
  	<%= form.file_field :image, :class => "imgloader" %>
  <div class="field">
    <%= form.label :content %>
  <%= form.cktext_area :content  %>
    <!-- <h4 class="form__block__title3">Описание</h4></div> -->


    <div class="field">
        <h4 class="form__block__title2">Название</h4>
        <%= form.text_field :title, :class => "form2" %>
      </div>


    <%= form.submit :class => "actions" %>


<% end %>

app/views/posts/edit.html.erb
<div class="titlenew">
<h1>Редактирование поста</h1>
</div>
<%= render 'form', post: @post %>
<div class="show">
<%= link_to 'Показать', @post %>
</div>
<div class="back">
<%= link_to 'Назад', posts_path %> |
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="link2">
  <%= link_to "о проекте", about_path %>
</div>
<div class="link1">
  <%= link_to "промо", promo_path %>
</div>
<div class="link3">
  <%= link_to "афиша", posts_path %>
</div>
<div class="link333">
<%= link_to "классы", directions_path %>
</div>

<% if user_signed_in? && current_user.isadmin == true %>
<%= link_to 'Новая категория', new_category_path %>
<%= link_to 'Новый пост', new_post_path %>
<% end %>


<!-- <div class="titlenew3">
<h1>Афиша</h1>
</div> -->
<!-- <div class="months">
  Ноябрь
</div> -->
<table>



  <h2>Афиша</h2>
  <% Category.all.each do |cat| %>
  	<%= link_to cat.name, posts_path(category: cat.name) %> <br>
  <% end %>

<!-- <th>Category</th> -->
  <tbody class="posts">

    <% @posts.each do |post| %>
    <td>
	<%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
</td>
<td>
	<%= post.comments.count %> <%= (post.comments.count) == 1 ? 'Comment' : 'Commentes'%>
</td>
    <td><%= post.category.name %></td>
      <tr class="posts__item">
<td><%= post.content.html_safe %></td>
        <td class="posts__item__text posts__item__text-theme"><%= post.name %></td>
         <td class="posts__item__text posts__item__text-title"><%= post.title %></td>
        

<td class="posts__item__links">

          <%= link_to 'Открыть', post, :class =>"link" %>

<% if user_signed_in? && current_user.isadmin == true %>

        <%= link_to 'Изменить', edit_post_path(post), :class =>"link" %>


        <%= link_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"link" %>
<% end %>
      </td>

      </tr>

  </tbody>
</table>


<% end %>

app/views/posts/new.html.erb
<div class="titlenew">
  <h1>Новое мероприятие</h1>
</div>


<%= render 'form', post: @post %>
<div class="back">
<%= link_to 'Назад', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="link22">
  <%= link_to "о проекте", about_path %>
</div>
<div class="link11">
  <%= link_to "промо", promo_path %>
</div>
<div class="link33">
  <%= link_to "афиша", posts_path %>
</div>

<div class="titlenew2">
<h1>
  <strong></strong>
  <%= @post.title %>
</h1>
</div>

  <strong></strong>
<h4 class="form__block__title15">  <%= @post.name %></h4>

<div class="showimg">
<%= image_tag(@post.image.url, alt: 'Image') if @post.image? %>
</div>



<p>
  <strong>Category:</strong>
  <%= @post.category.name %>
</p>


  <strong></strong>
<h4 class="form__block__title16">   <%= @post.content.html_safe %></h4>


<h4 class="form__block__title18">Комментарии</h4>
<%= render @post.comments %>
<div class="back2">
<%= link_to 'Назад', posts_path %> |
</div>
<div class="show2">
  <% if user_signed_in? %>
<%= link_to 'Редактировать', edit_post_path(@post) %> <% end %> </div>

<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<% if user_signed_in? %>
  <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>
  <% pre_favorite = @post.favorites.find { |favorite| favorite.user_id == current_user.id} %>
  <% if pre_favorite %>
      <%= button_to 'Remove from Favorite', post_favorite_path(@post, pre_favorite), method: :delete %>
  <% else %>
      <%= button_to 'Add to Favorite', post_favorites_path(@post), method: :post %>
  <% end %>
<% end %>

<h4 class="form__block__title17">
Добавить комментарий:
</h4>
<% if user_signed_in? %>
<%= render "comments/form" %>
<% else %>
<p>Please <%= link_to 'login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to comment.</p>
<% end %>